baseURL = 'https://adamanr.github.io/blog/'
languageCode = 'en-ru'
title = 'Adaman blog'
pygmentsCodeFences = true
pygmentsUseClasses = true
defaultContentLanguage = 'ru'

[params]
description = "ğŸ¦€ Rust  |  ğŸ§ª Elixir | ğŸ¦« Go"
author = "Artyom"
github = "#CEOCringeINC"
linkedin = "MeiK2333"
email = "Adamanq@yandex.ru"
url = "t.me/behind_the_circus"
keywords = "blog, google analytics"
rss = true
lastmod = true
favicon = "/blog/images/github-mark.png"
avatar = "/blog/images/avatar.png"
headerIcon = "/images/github-mark-white.png"
location = "Russia"
userStatusEmoji = "ğŸ¤¡"
userEmojiDesc = "Ğ¦Ğ¸Ñ€Ğº ÑƒĞµÑ…Ğ°Ğ», Ğ° ĞºĞ»Ğ¾ÑƒĞ½ Ğ¾ÑÑ‚Ğ°Ğ»ÑÑ"
enableGitalk = false
enableSearch = true
custom_css = ["/css/custom.css"]
translationKey = 'about'

[languages]
[languages.ru]
contentDir = 'content/russia'
languageName = 'Russia'
weight = 10
[languages.en]
contentDir = 'content/english'
languageName = 'English'
weight = 10


[[params.links]]
title = "Ğ—Ğ°ĞºÑƒĞ»Ğ¸ÑÑŒĞµ Ñ†Ğ¸Ñ€ĞºĞ°"
href = "https://t.me/behind_the_circus"
icon = "/images/circus.png"
[[params.links]]
title = "ĞœĞ¾Ğ¹ Ñ‚ĞµĞ»ĞµĞ³Ñ€Ğ°Ğ¼"
href = "https://t.me/Adamanq"
icon = "/images/adaman.jpg"

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[params.gitalk]
clientID = "Your client ID"                                                                 # Your client ID
clientSecret = "Your client secret"                                                         # Your client secret
repo = "LuvSia"                                                                             # æ‚¨çš„åšå®¢çš„githubåœ°å€Repository nameï¼Œä¾‹å¦‚ï¼šxxxx.github.io
owner = "ventusoon"                                                                         # æ‚¨çš„GitHub ID
admin = "ventusoon"                                                                         # æ‚¨çš„GitHub ID
id = "location.pathname"                                                                    # æ–‡ç« é¡µé¢çš„é“¾æ¥åœ°å€å°±æ˜¯ID
labels = "gitalk"                                                                           # Github issue labels. If you used to use Gitment, you can change it
perPage = 15                                                                                # Pagination size, with maximum 100.
pagerDirection = "last"                                                                     # Comment sorting direction, available values are 'last' and 'first'.
createIssueManually = true                                                                  # è®¾ç½®ä¸ºtrueï¼Œå¦‚æœæ˜¯ç®¡ç†å‘˜ç™»å½•ï¼Œä¼šè‡ªåŠ¨åˆ›å»ºissueï¼Œå¦‚æœæ˜¯falseï¼Œéœ€è¦ç®¡ç†å‘˜æ‰‹åŠ¨æ·»åŠ ç¬¬ä¸€ä¸ªè¯„è®º(issue)
distractionFreeMode = false                                                                 # Enable hot key (cmd|ctrl + enter) submit comment.
proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token" # å¯ä»¥è‡ªè¡Œæ·»åŠ åå‘ä»£ç†


[outputs]
home = ["HTML", "RSS", "JSON"]

[outputFormats.JSON]
mediaType = "application/json"
baseName = "index"
isPlainText = false


[services]
[services.googleAnalytics]
ID = "UA-123456-789"
